name: glory_convention_lint
description: GloryConventionLint is code judgment for Convention Lint Flutter.
version: 1.0.0
homepage: https://rollingglory.com/
repository: https://github.com/rollingglory/GloryConventionLint-flutter
issue_tracker: https://github.com/rollingglory/GloryConventionLint-flutter/issues
documentation: https://github.com/rollingglory/GloryConventionLint-flutter/blob/main/README.md


environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  analyzer_plugin: ^0.11.2
  collection: ^1.17.0
  custom_lint_builder: ^0.2.5
  matcher: ^0.12.13
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  custom_lint:
  lints: ^2.0.0

